### ISSUE TITLE
Label matcher stopped working

### ISSUE THREAD

**Issue by eduardojunio** [wip/app#265]
We use WIP to block PRs based on title terms and labels. For some reason, it suddenly stopped blocking PRs if the matching label is there. We suspect that it's the same problem that happened in the past (see #242).

Here is our `.github/wip.yml` file for reference:
```
- terms:
  - wip
  - Work in progress
  - 🚧
  locations: title
- terms:
  - qa needed
  - data migration
  - need simultaneous merge
  - waiting for code review
  - waiting for page tests
  locations: label_name
```
