### ISSUE TITLE
github/wip.yml is being ignored

### ISSUE THREAD

**Issue by genebean** [wip/app#498]
We have used the config below for several years now. Somewhat recently it has started to be ignored.

```yaml
---
locations:
  - title
  - label_name
  - commit_subject
terms:
  - wip
  - work in progress
  - 🚧
  - do not merge
  - ⛔
  - needs testing
  - needs work
  - change-freeze
  - merge on Monday

```

Is there anything I can do to help troubleshoot this?
