### ISSUE TITLE
⚙ Configuration

### ISSUE THREAD

**Issue by gr2m** [wip/app#96]
I’m in the process of submitting the WIP app to the Marketplace. The new version will support configuration and I’d like to invite y’all to discuss what the configuration should look like. Please share your workflows and how WIP would ideally work to seamlessly integrate with it :)

Right now I see two things that should be configurable

1. The terms that the WIP app will look for (by default "WIP", "Work in progress" and "Do not merge", case insensitive)
2. The locations that the WIP app will check for the configured terms (by default only the pull request title)

The configuration will be done via a `.github/wip.yml` file in your repository. See https://github.com/probot/probot-config for how configuration works with Probot and [stale app usage](https://github.com/probot/stale#usage) for an example

### Example configuration

This is my base of discussion, please comment below if it that works for you or if you have any questions/suggestions

```yaml
# Configuration for WIP - https://github.com/wip/app

# List of terms that will make WIP set a pull request status to "pending".
# All terms are work in case insensitive and will be matched as whole words,
# e.g. "WIP" will match "wip: refactoring" but not "Add swipe feature"
terms: 
- WIP
- Work in progress
- Do not merge

# List of places that WIP will check for the terms defined above
# Possible values are
# - title            (pull request title)
# - labels           (label names)
# - commit_subjects  (commit subjects)
check:
- title
```

### Discussion

I’m not happy with the term "check". Maybe someone has a better idea?

**Comment by blairconrad** [comment]
@gr2m, I like the configuration file location.

The configuration looks good, and easy to understand. This is added complexity, but have you considered allowing the application of different terms to each check location? Probably more bother than it's worth…

Regarding this issue's relation to #55, I take it I could then configure like this to replicate the behaviour I was interested in?

```
terms:
- fixup!
- squash!

check:
- commits
```

Thanks!

**Comment by gr2m** [comment]
I think for the usecase to block PRs if there are commits with "fixup!" or "squash!" it works good enough to add them to the `terms` config. I don’t think there is a chance for false positives that these terms could be found in labels or the pull request title

**Comment by erikstrottmann** [comment]
As an alternate name for `check`, what do you think about `locations`? Then both configuration options would be nouns, not a noun and a verb.

---

The option `commits` is slightly unintuitive if it only refers to commit subjects. I don’t have a strong opinion between the following:

- changing the option to also search commit bodies
- renaming the option to something like `commit_subjects`
- renaming the option, and also adding a `commit_bodies` option

---

My team’s workflow is to not allow merging if there’s a “hold” label, a “fixup!” or “squash!” commit, or “WIP” in the PR title or a commit. I’m not concerned about false positives for “fixup!”, “squash!”, or “WIP”, but I could see “hold” being used for unrelated reasons in commit titles. A potential syntax for configuration per check location could look like:

 ```yaml
-
  terms:
    - hold
  locations:
    - label
-
  terms:
    - fixup!
    - squash!
  locations:
    - commits
-
  terms:
    - WIP
  locations:
    - title
    - commit
```

That is, each set of term/location pairs would be a list item.
